FileVersion = 1

[Project]
Name = "jsmn-beef"
TargetType = "BeefLib"
StartupObject = "jsmn_beef.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\jsmn_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\jsmn.lib"]
